name: CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build:
    name: Build, lint, and test on Node ${{ matrix.node }}

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ["14.x", "16.x"]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Run Nigiri
        uses: vulpemventures/nigiri-github-action@v1

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Lint
        run: |
          yarn format:ci
          yarn lint
          yarn lint:tests

      - name: Build
        run: yarn build

      - name: Coverage
        run: yarn nobuild:coverage

      - name: Unit Test
        run: yarn nobuild:unit

      - name: Integration Test
        env:
          APIURL: http://localhost:3001
        run: yarn nobuild:integration
